name: main
on:
  # schedule:
  #   - cron:  '*/20 * * * *'
  workflow_dispatch:
  push:
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r $GITHUB_WORKSPACE/src/requirements.txt
          python -m playwright install chromium
      - run: python $GITHUB_WORKSPACE/src/main.py
      - run: |
          if [[ `git diff --exit-code data/site.json` ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add data/site.json
            git commit -m "Automated update of site data"
            git push
          fi
